[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
# DEFMT_LOG = "warn" # touch Cargo.toml to rebuild cmk


[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip=RP2040"


rustflags = [
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tlink-rp.x",
    "-C",
    "link-arg=-Tdefmt.x",
]
